api/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url

from api.views import ApiEndpoint, UserList

urlpatterns = [
    # OAuth 2 endpoints:
    url(r'^hello/$', ApiEndpoint.as_view()),  # an example resource endpoint
    url(r'^users/$', UserList.as_view()),
    url(r'^users/(?P<pk>\d+)/$', UserList.as_view()),
    url(r'^groups/$', UserList.as_view()),
]

assets/urls.py
from django.conf.urls import url

from assets import views

urlpatterns = [
    url(r'^report/', views.report, name='report'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^index/', views.index, name='index'),
    url(r'^detail/(?P<asset_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^$', views.dashboard),
]

cmdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^assets/', include('assets.urls', namespace='assets')),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

assets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Asset(models.Model):
    """    所有资产的共有数据表    """
    asset_type_choice = (
        ('server', _('Server')),  # 服务器
        ('networkdevice', _('Network device')),  # 网络设备
        ('storagedevice', _('Storage device')),  # 存储设备
        ('securitydevice', _('Security device')),  # 安全设备
        ('software', _('Asset software')),  # 软件资产
    )

    asset_status = (
        (0, _('Online')),  # 在线
        (1, _('Offline')),  # 下线
        (2, _('Unknown')),  # 未知
        (3, _('Breakdown')),  # 故障
        (4, _('Spare')),  # 备用
    )

    asset_type = models.CharField(choices=asset_type_choice, max_length=64, default='server',
                                  verbose_name=_('Asset type'))  # 资产类型
    name = models.CharField(max_length=64, unique=True, verbose_name=_('Asset name'))  # 资产名称
    sn = models.CharField(max_length=128, unique=True, verbose_name=_('Asset serial number'))  # 资产序列号
    business_unit = models.ForeignKey('BusinessUnit', null=True, blank=True, verbose_name=_('Business unit'))  # 所属业务线
    status = models.SmallIntegerField(choices=asset_status, default=0, verbose_name=_('Device status'))  # 设备状态

    manufacturer = models.ForeignKey('Manufacturer', null=True, blank=True, verbose_name=_('Manufacturer'))  # 制造商
    manage_ip = models.GenericIPAddressField(null=True, blank=True, verbose_name=_('Manage IP'))  # 管理IP
    tags = models.ManyToManyField('Tag', blank=True, verbose_name=_('Tag'))  # 标签
    admin = models.ForeignKey(User, null=True, blank=True, verbose_name=_('Asset admin'), related_name='admin')  # 资产管理员
    idc = models.ForeignKey('IDC', null=True, blank=True, verbose_name=_('IDC'))  # 所在机房
    contract = models.ForeignKey('Contract', null=True, blank=True, verbose_name=_('Contract'))  # 合同

    purchase_day = models.DateField(null=True, blank=True, verbose_name=_('Purchase day'))  # 购买日期
    expire_day = models.DateField(null=True, blank=True, verbose_name=_('Expire day'))  # 过保日期
    price = models.FloatField(null=True, blank=True, verbose_name=_('Price'))  # 价格

    approved_by = models.ForeignKey(User, null=True, blank=True, verbose_name=_('Approver'),
                                    related_name='approved_by')  # 批准人

    memo = models.TextField(null=True, blank=True, verbose_name=_('Memo'))  # 备注
    c_time = models.DateTimeField(auto_now_add=True, verbose_name=_('Approval date'))  # 批准日期
    m_time = models.DateTimeField(auto_now=True, verbose_name=_('Modify date'))  # 更新日期

    def __unicode__(self):
        return '<%s>  %s' % (self.get_asset_type_display(), self.name)

    class Meta:
        verbose_name = _('Asset summary statement')  # 资产总表
        verbose_name_plural = _('Asset summary statements')  # 资产总表
        ordering = ['-c_time']


class Server(models.Model):
    """    服务器设备    """
    sub_asset_type_choice = (
        (0, _('PC Server')),  # PC服务器
        (1, _('Blade')),  # 刀片机
        (2, _('Minicomputer')),  # 小型机
    )

    created_by_choice = (
        ('auto', _('Automatically add')),  # 自动添加
        ('manual', _('Manual input')),  # 手工录入
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0,
                                              verbose_name=_('Server type'))  # 服务器类型
    created_by = models.CharField(choices=created_by_choice, max_length=32, default='auto',
                                  verbose_name=_('Add mode'))  # 添加方式
    # 虚拟机专用字段
    hosted_on = models.ForeignKey('self', related_name='hosted_on_server', blank=True, null=True,
                                  verbose_name=_('Host'))  # 宿主机
    model = models.CharField(max_length=128, null=True, blank=True, verbose_name=_('Server model'))  # 服务器型号
    raid_type = models.CharField(max_length=512, blank=True, null=True, verbose_name=_('Raid type'))  # Raid类型

    os_type = models.CharField(max_length=64, blank=True, null=True, verbose_name=_('OS type'))  # 操作系统类型
    os_distribution = models.CharField(max_length=64, blank=True, null=True, verbose_name=_('OS distribution'))  # 发行版本
    os_release = models.CharField(max_length=64, blank=True, null=True, verbose_name=_('OS release'))  # 操作系统版本

    def __unicode__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = _('Server')  # 服务器
        verbose_name_plural = _('Servers')  # 服务器


class SecurityDevice(models.Model):
    """    安全设备    """
    sub_asset_type_choice = (
        (0, _('Fire wall')),  # 防火墙
        (1, _('Intrusion detection device')),  # 入侵检测设备
        (2, _('Internet gateway')),  # 互联网网关
        (4, _('SSA')),  # 运维审计系统
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0,
                                              verbose_name=_('Security device type'))  # 安全设备类型

    def __unicode__(self):
        return self.asset.name + '--' + self.get_sub_asset_type_display() + ' id:%s' % self.id

    class Meta:
        verbose_name = _('Security device')  # 安全设备
        verbose_name_plural = _('Security devices')  # 安全设备


class StorageDevice(models.Model):
    """    存储设备    """
    sub_asset_type_choice = (
        (0, _('Disk array')),  # 磁盘阵列
        (1, _('Network memorizer')),  # 网络存储器
        (2, _('Tape library')),  # 磁带库
        (4, _('Tape streamer')),  # 磁带机
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0,
                                              verbose_name=_('Storage device type'))  # 存储设备类型

    def __unicode__(self):
        return self.asset.name + '--' + self.get_sub_asset_type_display() + ' id:%s' % self.id

    class Meta:
        verbose_name = _('Storage device')  # 存储设备
        verbose_name_plural = _('Storage devices')  # 存储设备


class NetworkDevice(models.Model):
    """    网络设备    """
    sub_asset_type_choice = (
        (0, _('Router')),  # 路由器
        (1, _('Switches')),  # 交换机
        (2, _('Load balancing')),  # 负载均衡
        (4, _('VPN device')),  # VPN设备
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0,
                                              verbose_name=_('Network device type'))  # 网络设备类型

    # 局域网 IP
    vlan_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name=_('VLanIP'))  # 局域网 IP
    intranet_ip = models.GenericIPAddressField(blank=True, null=True, verbose_name=_('Intranet IP'))  # 内网IP

    model = models.CharField(max_length=128, null=True, blank=True, verbose_name=_('Network device model'))  # 网络设备型号
    firmware = models.CharField(max_length=128, blank=True, null=True,
                                verbose_name=_('Device firmware edition'))  # 设备固件版本
    port_num = models.SmallIntegerField(null=True, blank=True, verbose_name=_('Port number'))  # 端口个数
    device_detail = models.TextField(null=True, blank=True, verbose_name=_('Detailed configuration'))  # 详细配置

    def __unicode__(self):
        return '%s--%s--%s <sn:%s>' % (self.asset.name, self.get_sub_asset_type_display(), self.model, self.asset.sn)

    class Meta:
        verbose_name = _('Network device')  # 网络设备
        verbose_name_plural = _('Network devices')  # 网络设备


class Software(models.Model):
    """    只保存付费购买的软件    """
    sub_asset_type_choice = (
        (0, _('OS')),  # 操作系统
        (1, _('Office/Development software')),  # 办公/开发软件
        (2, _('Business software')),  # 业务软件
    )

    asset = models.OneToOneField('Asset')
    sub_asset_type = models.SmallIntegerField(choices=sub_asset_type_choice, default=0,
                                              verbose_name=_('Software type'))  # 软件类型
    license_num = models.IntegerField(default=1, verbose_name=_('License number'))  # 授权数量
    version = models.CharField(max_length=64, unique=True, help_text=u'例如: CentOS release 6.7 (Final)',
                               verbose_name=_('Software/OS release'))  # 软件/系统版本

    def __unicode__(self):
        return '%s--%s' % (self.get_sub_asset_type_display(), self.version)

    class Meta:
        verbose_name = _('Software/OS')  # 软件/系统
        verbose_name_plural = _('Software/OS')  # 软件/系统


class IDC(models.Model):
    """    机房    """
    name = models.CharField(max_length=64, unique=True, verbose_name=_('IDC name'))  # 机房名称
    memo = models.CharField(max_length=128, blank=True, null=True, verbose_name=_('Memo'))  # 备注

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('IDC')  # 机房
        verbose_name_plural = _('IDC')  # 机房


class Manufacturer(models.Model):
    """    厂商    """
    name = models.CharField(_('Manufacturer name'), max_length=64, unique=True)  # 厂商名称
    telephone = models.CharField(_('Support telephone'), max_length=30, blank=True, null=True)  # 支持电话
    memo = models.CharField(_('Memo'), max_length=128, blank=True, null=True)  # 备注

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Manufacturer')  # 厂商
        verbose_name_plural = _('Manufacturers')  # 厂商


class BusinessUnit(models.Model):
    """    业务线    """
    parent_unit = models.ForeignKey('self', blank=True, null=True, related_name='parent_level')
    name = models.CharField(_('Line of business'), max_length=64, unique=True)  # 业务线
    memo = models.CharField(_('Memo'), max_length=64, blank=True, null=True)  # 备注

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = _('Line of business')  # 业务线
        verbose_name_plural = _('Line of businesses')  # 业务线


class Contract(models.Model):
    """    合同    """

assets/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_exempt

from assets import models, asset_handler


@csrf_exempt
def report(request):
    """
    通过csrf_exempt装饰器，跳过Django的csrf安全机制，让post的数据能被接收，但这又会带来新的安全问题。
    可以在客户端，使用自定义的认证token，进行身份验证。这部分工作，请根据实际情况，自己进行。
    :param request:
    :return:
    """
    if request.method == "POST":
        asset_data = request.POST.get('asset_data')
        data = json.loads(asset_data)
        # 各种数据检查，请自行添加和完善！
        if not data:
            return HttpResponse(_('Data not found'))
        if not issubclass(dict, type(data)):
            return HttpResponse(_('Data must be dict'))
        # 是否携带了关键的sn号
        sn = data.get('sn', None)
        if sn:
            # 进入审批流程
            # 首先判断是否在上线资产中存在该sn
            asset_obj = models.Asset.objects.filter(sn=sn)
            if asset_obj:
                # 进入已上线资产的数据更新流程
                update_asset = asset_handler.UpdateAsset(request, asset_obj[0], data)
                return HttpResponse(_('Asset data has updated'))
            else:  # 如果已上线资产中没有，那么说明是未批准资产，进入新资产待审批区，更新或者创建资产。
                obj = asset_handler.NewAsset(request, data)
                response = obj.add_to_new_assets_zone()
                return HttpResponse(response)
        else:
            return HttpResponse(_('Serial number not found, please check data'))
    else:
        return HttpResponse(_('Only post method'))


def index(request):
    assets = models.Asset.objects.exclude(asset_type='software').all()
    return render(request, 'assets/index.html', locals())


def dashboard(request):
    total = models.Asset.objects.count()
    upline = models.Asset.objects.filter(status=0).count()
    offline = models.Asset.objects.filter(status=1).count()
    unknown = models.Asset.objects.filter(status=2).count()
    breakdown = models.Asset.objects.filter(status=3).count()
    backup = models.Asset.objects.filter(status=4).count()
    up_rate = round(float(upline) / float(total) * 100)
    o_rate = round(float(offline) / float(total) * 100)
    un_rate = round(float(unknown) / float(total) * 100)
    bd_rate = round(float(breakdown) / float(total) * 100)
    bu_rate = round(float(backup) / float(total) * 100)
    server_number = models.Server.objects.count()
    networkdevice_number = models.NetworkDevice.objects.count()
    storagedevice_number = models.StorageDevice.objects.count()
    securitydevice_number = models.SecurityDevice.objects.count()
    software_number = models.Software.objects.count()

    return render(request, 'assets/dashboard.html', locals())


def detail(request, asset_id):
    """
    以显示服务器类型资产详细为例，安全设备、存储设备、网络设备等参照此例。
    :param request:
    :param asset_id:
    :return:
    """
    asset = get_object_or_404(models.Asset, id=asset_id)
    return render(request, 'assets/detail.html', locals())

assets/templates/assets/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}资产详细{% endblock %}
{% block css %}

  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

{% endblock %}

{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        资产详细
        <small>asset info</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>资产总表</li>
        <li class="active">资产详细</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"><strong class="btn btn-block btn-primary btn-lg">资产：{{ asset.name }}</strong></h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          <h4><b>概览:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue" >
                <thead>
                    <tr>
                        <th>类型</th>
                        <th>SN</th>
                        <th>业务线</th>
                        <th>制造商</th>
                        <th>管理IP</th>
                        <th>机房</th>
                        <th>标签</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.get_asset_type_display }}</td>
                    <td>{{ asset.sn }}</td>
                    <td>{{ asset.business_unit|default:'N/A' }}</td>
                    <td>{{ asset.manufacturer|default:'N/A' }}</td>
                    <td>{{ asset.manage_ip|default:'N/A' }}</td>
                    <td>{{ asset.idc|default:'N/A' }}</td>
                    <td>
                        {% for tag in asset.tags.all %}
                        <label class="label label-primary">{{ tag.name }}</label>
                        {% empty %}
                            -
                        {% endfor %}
                    </td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
            <br />
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue">
                <thead>
                    <tr>
                        <th>合同</th>
                        <th>价格</th>
                        <th>购买日期</th>
                        <th>过保日期</th>
                        <th>管理员</th>
                        <th>批准人</th>
                        <th>备注</th>
                        <th>批准日期</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.contract.name|default:'N/A' }}</td>
                    <td>{{ asset.price|default:'N/A' }}</td>
                    <td>{{ asset.purchase_day|default:'N/A' }}</td>
                    <td>{{ asset.expire_day|default:'N/A' }}</td>
                    <td>{{ asset.admin|default:'N/A' }}</td>
                    <td>{{ asset.approved_by|default:'N/A' }}</td>
                    <td>{{ asset.memo|default:'N/A' }}</td>
                    <td>{{ asset.m_time }}</td>
                </tr>
                </tbody>
            </table>
          <h4><b>服务器:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid green;border-bottom:1px solid green">
                <thead>
                    <tr>
                        <th>服务器类型</th>
                        <th>型号</th>
                        <th>宿主机</th>
                        <th>Raid类型</th>
                        <th>OS类型</th>
                        <th>OS发行版本</th>
                        <th>OS版本</th>
                        <th>添加方式</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.server.get_sub_asset_type_display }}</td>
                    <td>{{ asset.server.model|default:'N/A' }}</td>
                    <td>{{ asset.server.hosted_on.id|default:'N/A' }}</td>
                    <td>{{ asset.server.raid_type|default:'N/A' }}</td>
                    <td>{{ asset.server.os_type|default:'N/A' }}</td>
                    <td>{{ asset.server.os_distribution|default:'N/A' }}</td>
                    <td>{{ asset.server.os_release|default:'N/A' }}</td>
                    <td>{{ asset.server.get_created_by_display }}</td>
                </tr>
                </tbody>
            </table>
        <h4><b>CPU:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid purple;border-bottom:1px solid purple">
                <thead>
                    <tr>
                        <th  style="width: 45%">CPU型号</th>
                        <th  style="width: 15%">物理CPU个数</th>
                        <th>CPU核数</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.cpu.cpu_model|default:'N/A' }}</td>
                    <td>{{ asset.cpu.cpu_count|default:'1' }}</td>
                    <td>{{ asset.cpu.cpu_core_count|default:'1' }}</td>
                </tr>
                </tbody>
            </table>
        <h4><b>内存:</b></h4>
        <table border="1" class="table  table-responsive" style="border-left:3px solid orangered;border-bottom:1px solid orangered">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for ram in asset.ram_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ ram.model|default:'N/A' }}</td>
                        <td>{{ ram.capacity|default:'N/A' }}</td>
                        <td>{{ ram.slot }}</td>
                        <td>{{ ram.manufacturer|default:'N/A' }}</td>
                        <td>{{ ram.sn|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        <h4><b>硬盘:</b></h4>
        <table border="1" class="table  table-responsive" style="border-left:3px solid brown;border-bottom:1px solid brown">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>型号</th>
                        <th>容量</th>
                        <th>插槽</th>
                        <th>接口类型</th>
                        <th>制造商</th>
                        <th>SN</th>
                    </tr>
                </thead>
                <tbody>
                {% for disk in asset.disk_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ disk.model|default:'N/A' }}</td>
                        <td>{{ disk.capacity|default:'N/A' }}</td>
                        <td>{{ disk.slot|default:'N/A'  }}</td>
                        <td>{{ disk.get_interface_type_display }}</td>
                        <td>{{ disk.manufacturer|default:'N/A' }}</td>
                        <td>{{ disk.sn}}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        <h4><b>网卡:</b></h4>
        <table border="1" class="table  table-responsive" style="border-left:3px solid #a59b1a;border-bottom:1px solid #a59b1a">
                <thead>
                    <tr>
                        <th style="width:5%;">序号</th>
                        <th>名称</th>
                        <th>型号</th>
                        <th>MAC</th>
                        <th>IP</th>
                        <th>掩码</th>
                        <th>绑定地址</th>
                    </tr>
                </thead>
                <tbody>
                {% for nic in asset.nic_set.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ nic.name|default:'N/A' }}</td>
                        <td>{{ nic.model }}</td>
                        <td>{{ nic.mac  }}</td>
                        <td>{{ nic.ip_address|default:'N/A' }}</td>
                        <td>{{ nic.net_mask|default:'N/A' }}</td>
                        <td>{{ nic.bonding|default:'N/A' }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td></td><td></td><td></td><td></td><td></td><td></td><td></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-angle-double-left"></i>&nbsp;&nbsp;<a href="{% url 'assets:index' %}"><strong>返回资产列表页</strong></a>
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->

{% endblock %}




{% block script %}
    <!-- SlimScroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'dist/js/demo.js' %}"></script>
    <!-- page script -->
{% endblock %}